### ISSUE TITLE
Update README to indicate only approved strings copied

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-labs/weblate-migration-scripts#2]
I think https://github.com/artefactual-labs/weblate-migration-scripts/blob/master/README.md#copy-xliff-files-from-weblate-repo-into-atom needs to be updated to indicate that only approved strings are are copied to the AtoM repo?

**Comment by mcantelon** [comment]
Fixed in https://github.com/artefactual-labs/weblate-migration-scripts/commit/b424141a3304210e9c6a5b1db23e7da6d77edebf
